### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by EntityinArray** [jsburger/Architects-Palette#43]
Judging from the error message, mod is expecting some OwoItemGroup that is not installed
Handle missing mods you depend on properly
```
---- Minecraft Crash Report ----
// Daisy, daisy...
Time: 2023-09-13 20:29:34
Description: Initializing game
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'architects_palette'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: java.lang.NoClassDefFoundError: io/wispforest/owo/itemgroup/OwoItemGroup
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more
Caused by: java.lang.ClassNotFoundException: io.wispforest.owo.itemgroup.OwoItemGroup
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 17 more
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)
-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (amd64) version 6.5.3-zen1-1-zen
	Java Version: 17.0.7, Flathub
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Flathub
	Memory: 385303184 bytes (367 MiB) / 916455424 bytes (874 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5700G with Radeon Graphics
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: GA104 [GeForce RTX 3060]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MB): 288.00
	Graphics card #0 deviceId: 0x2487
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 40568.53
	Virtual memory used (MB): 7444.29
	Swap memory total (MB): 24576.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms512m -Xmx4096m
	Fabric Mods: 
		ad_astra: Ad Astra 1.12.7
		ad_astra_giselle_addon: Ad Astra: Giselle Addon 1.18
		adaptive-tooltips: Adaptive Tooltips 1.0.1
		advdebug: Advancements Debug 2.3.0
		ae2: Applied Energistics 2 12.9.8
			noindium: No Indium? 1.1.0+1.19
		ae2wtlib: AE2WTLib 12.9.5
		almostunified: AlmostUnified 1.19.2-0.6.0
		alternate-current: Alternate Current 1.7.0
		another_furniture: Another Furniture 1.19.2-2.1.4
		antighost: AntiGhost 1.19.1-fabric0.58.5-1.1.5
			crowdin-translate: CrowdinTranslate 1.4+1.19
		appleskin: AppleSkin 2.4.1+mc1.19
		architects_palette: Architect's Palette Fabric 3.0.0
		architectury: Architectury 6.5.85
		artifacts: Artifacts 7.1.1+fabric
			cardinal-components-base: Cardinal Components API (base) 5.0.0-beta.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.0-beta.1
			expandability: ExpandAbility 6.0.0
			step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		asynclocator: Async Locator 1.3.1
		attributefix: AttributeFix 17.2.7
		authme: Auth Me 4.2.0
		autoconfig1u: Auto Config v1 Updated 3.4.0
		awesomedungeon: Awesome dungeon 3.2.0
		axolotlitemfix: Axolotl Item Fix 1.1.4
		badpackets: Bad Packets 0.2.2
		balm-fabric: Balm 4.5.7
		beaconoverhaul: Beacon Overhaul 1.7.3+1.19.2
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		beenfo: Beenfo 1.19.1-fabric0.58.5-1.3.3
			gbfabrictools: GBfabrictools 1.3.4+1.19
		betteradvancements: Better Advancements 0.3.0.148
		bettercombat: Better Combat 1.7.1+1.19
		betterdeserttemples: YUNG's Better Desert Temples 1.19.2-Fabric-2.2.2
			org_reflections_reflections: reflections 0.10.2
		betterfpsdist: Better FPS distance Mod 1.19-2.4
		bettermounthud: Better Mount HUD 1.2.0
		betterpingdisplay: Better Ping Display 1.1.1
		betterstats: Better Statistics Screen 2.9.3+1.19.2
			tcdcommons: TCD Commons API 2.9.1+1.19.2
		blockus: Blockus 2.5.11+1.19.2
			terraform-wood-api-v1: Terraform Wood API (v1) 4.2.0
		blur: Blur (Fabric) 2.6.0
			midnightlib: MidnightLib 0.5.2
			satin: Satin 1.8.0
		bookshelf: Bookshelf 16.3.20
		botarium: Botarium 1.8.2
			team_reborn_energy: Energy 2.2.0
		bowinfinityfix: Bow Infinity Fix 2.5.0
		bwncr: Bad Wither No Cookie Reloaded 3.14.1
		cloth-api: Cloth API 4.0.65
			cloth-basic-math: cloth-basic-math 0.6.1
			cloth-client-events-v0: Cloth Client Events v0 4.0.65
			cloth-common-events-v1: Cloth Common Events v1 4.0.65
			cloth-scissors-api-v1: Cloth Scissors API v1 4.0.65
			cloth-utils-v1: Cloth Utils v1 4.0.65
		cloth-config: Cloth Config v8 8.3.103
		fabric-api: Fabric API 0.76.1+1.19.2
			fabric-api-base: Fabric API Base 0.4.15+8f4e8eb390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.14+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.1+16f1e31390
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.25+cafc6e8e90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.5+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.16+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.33+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.42+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.2+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.3.0+4bc6e26290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.9+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.35+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.4+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.34+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.36+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.6+b7d1888890
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.39+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.4+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.13+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.16+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.7+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.24+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.21+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.12+def3f86d90
			fabric-networking-v0: Fabric Networking (v0) 0.3.29+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.2+d8ef690890
			fabric-particles-v1: Fabric Particles (v1) 1.0.14+4d0d570390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.2+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.33+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.1+1adbf27790
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.8.0+1adbf27790
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.24+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.19+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.11+4d0d570390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.27+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.1+d8ef690890
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.4+edbdcddb90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.32+4d0d570390
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.8+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.24+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.6+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabricloader: Fabric Loader 0.14.22
		java: OpenJDK 64-Bit Server VM 17
		libraryferret: Library ferret 4.0.0
		minecraft: Minecraft 1.19.2
		modernfix: ModernFix 5.7.2+mc1.19.2
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.9
		player-animator: Player Animator 1.0.2
		resourcefulconfig: Resourcefulconfig 1.0.20
		resourcefullib: Resourceful Lib 1.1.24
		skinlayers: 3d Skin Layers 1.5.2-mc1.19.1
		trinkets: Trinkets 3.4.2
		yet-another-config-lib: YetAnotherConfigLib 2.2.0-for-1.19.2
		yungsapi: YUNG's API 1.19.2-Fabric-3.8.9
			org_javassist_javassist: javassist 3.28.0-GA
	Launched Version: 1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# /home/entityinarray/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/StaTech Industry/minecraft/crash-reports/crash-2023-09-13_20.29.34-client.txt
Process exited with code 255.

```

**Comment by jsburger** [comment]
This is an issue for the Fabric port, which I do not maintain. You should report the missing dependency on the Fabric repo.
